version: '2.1'
services:
  portal:
    image: nginx
    ports:
     - "8080:80"
    volumes:
     - ../tomcat-p2p-manager-based-session-replication/default.conf:/etc/nginx/conf.d/default.conf
    links:
     - tomcatServerOne:tomcat1
     - tomcatServerTwo:tomcat2
  tomcatServerOne:
    image: tomcat:8.5-jre8
    ports:
     - "8080"
    volumes:
     - ../target/example.war:/usr/local/tomcat/webapps/example.war
     - ../tomcat-p2p-manager-based-session-replication/hazelcast-tomcat85-sessionmanager-1.1.1.jar:/usr/local/tomcat/lib/hazelcast-tomcat85-sessionmanager-1.1.1.jar
     - ../tomcat-p2p-manager-based-session-replication/hazelcast-all-3.8.3.jar:/usr/local/tomcat/lib/hazelcast-all-3.8.3.jar
     - ../tomcat-p2p-manager-based-session-replication/server.xml:/usr/local/tomcat/conf/server.xml
     - ../tomcat-p2p-manager-based-session-replication/context.xml:/usr/local/tomcat/conf/context.xml
  tomcatServerTwo:
    image: tomcat:8.5-jre8
    ports:
     - "8080"
    volumes:
     - ../target/example.war:/usr/local/tomcat/webapps/example.war
     - ../tomcat-p2p-manager-based-session-replication/hazelcast-tomcat85-sessionmanager-1.1.1.jar:/usr/local/tomcat/lib/hazelcast-tomcat85-sessionmanager-1.1.1.jar
     - ../tomcat-p2p-manager-based-session-replication/hazelcast-all-3.8.3.jar:/usr/local/tomcat/lib/hazelcast-all-3.8.3.jar
     - ../tomcat-p2p-manager-based-session-replication/server.xml:/usr/local/tomcat/conf/server.xml
     - ../tomcat-p2p-manager-based-session-replication/context.xml:/usr/local/tomcat/conf/context.xml
