version: '2.1'
services:
 management-center:
    image: hazelcast/management-center
    volumes:
     - ../management-center-jaas/resources/security.properties:/data/security.properties
     - ../management-center-jaas/resources/jaas.properties:/data/jaas.properties
     - ../management-center-jaas/target/management-center-jaas-0.1-SNAPSHOT.jar:/opt/lib/management-center-jaas-0.1-SNAPSHOT.jar
     - ../management-center-jaas/resources/users.csv:/opt/users.csv
    ports:
     - 8080:8080
