portal:
  image: nginx
  ports:
   - "8080:80"
  volumes:
   - ../tomcat-deployment/default.conf:/etc/nginx/conf.d/default.conf
  links:
   - tomcatOne:tomcat1
   - tomcatTwo:tomcat2
tomcatOne:
  image: tomcat:8.5-jre8
  ports:
   - "8080"
  volumes:
   - ../target/session-replication.war:/usr/local/tomcat/webapps/session-replication.war

tomcatTwo:
  image: tomcat:8.5-jre8
  ports:
   - "8080"
  volumes:
   - ../target/session-replication.war:/usr/local/tomcat/webapps/session-replication.war
